In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (2.1.0)
Requirement already satisfied: bleach in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kaggle) (1.19.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kaggle) (0.1.22)
Requirement already satisfied: packaging in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kaggle) (6.33.5)
Requirement already satisfied: python-dateutil in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kaggle) (2.6.3)
Requirement already satisfied: webencodings in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from jupytext->kaggle) (4.0.0)
Requirement already satisfied: mdit-py-plugins in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.9.2)
Requirement already satisfied: typing-extensions>=4.4.0 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)
Requirement already satisfied: six>=1.5 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from requests->kaggle) (2026.1.4)

In [2]:
!pip install kagglehub

Requirement already satisfied: kagglehub in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (1.0.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kagglehub) (0.1.22)
Requirement already satisfied: packaging in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (6.33.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/hatem/miniconda3/envs/tf/lib/python3.12/site-packages (from requests->kagglehub) (2026.1.4)

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nitaisatapathy/welfake-dataset")

print("Path to dataset files:", path)

Path to dataset files: /home/hatem/.cache/kagglehub/datasets/nitaisatapathy/welfake-dataset/versions/1

In [4]:
import os

print(os.listdir(path))

['WELFake_Dataset.csv']

In [5]:
import pandas as pd 

df = pd.read_csv(f"{path}/WELFake_Dataset.csv")
df.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [6]:
df.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [7]:
df['title'].isnull().sum()

np.int64(558)

In [8]:
df.isnull().sum()

Unnamed: 0      0
title         558
text           39
label           0
dtype: int64

In [9]:
df = df.dropna()
df.isnull().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [10]:
df[df["label"] == 0].head(2)

,Unnamed: 0,title,text,label
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
11,11,"May Brexit offer would hurt, cost EU citizens ...",BRUSSELS (Reuters) - British Prime Minister Th...,0

In [11]:
df["content"] = (
    "Title: " + df["title"].fillna("") +
    " [SEP] Body: " + df["text"].fillna("")
)

In [12]:
df.head()

,Unnamed: 0,title,text,label,content
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1,Title: LAW ENFORCEMENT ON HIGH ALERT Following...
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1,Title: UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL ...
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0,"Title: Bobby Jindal, raised Hindu, uses story ..."
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1,Title: SATAN 2: Russia unvelis an image of its...
5,5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...,1,Title: About Time! Christian Group Sues Amazon...

In [13]:
print(df["content"].iloc[3])

Title: SATAN 2: Russia unvelis an image of its terrifying new ‘SUPERNUKE’ – Western world takes notice [SEP] Body: The RS-28 Sarmat missile, dubbed Satan 2, will replace the SS-18 Flies at 4.3 miles (7km) per sec and with a range of 6,213 miles (10,000km) The weapons are perceived as part of an increasingly aggressive Russia It could deliver a warhead of 40 megatons – 2,000 times as powerful as the atom bombs dropped on Hiroshima and Nagasaki in 1945 By LIBBY PLUMMER and GARETH DAVIE S Russia has unveiled chilling pictures of its largest ever nuclear missile, capable of destroying an area the size of France. The RS-28 Sarmat missile, dubbed Satan 2 by Nato, has a top speed of 4.3 miles (7km) per second and has been designed to outfox anti-missile shield systems. The new Sarmat missile could deliver warheads of 40 megatons – 2,000 times as powerful as the atom bombs dropped on Hiroshima and Nagasaki in 1945. Scroll down for video Russian President Vladimir Putin is reportedly planning to replace the country’s older SS-18 Satan weapons with the new missiles amid a string of recent disagreements with the West. The Kremlin has stepped up the rhetoric against the West and carried a series of manoeuvres that has infuriated politicians in the US and UK. The pictures were revealed online by chief designers from the Makeyev Rocket Design Bureau. A message posted alongside the picture said: ‘In accordance with the Decree of the Russian Government ‘On the State Defense Order for 2010 and the planning period 2012-2013’, the Makeyev Rocket Design Bureau was instructed to start design and development work on the Sarmat. ‘ The RS-28 Sarmat missile is said to contain 16 nuclear warheads and is capable of destroying an area the size of France or Texas, according to Russian news network Zvezda, which is owned by Russia’s ministry of defence. The weapon is also able to evade radar. It is expected to have a range of 6,213 miles (10,000 km), which would allow Moscow to attack London and
FOR ENTIRE ARTICLE CLICK LINK

In [29]:
from transformers import BertTokenizer, BertForSequenceClassification


tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

model = BertForSequenceClassification.from_pretrained(
    'bert-base-uncased',
    num_labels=2
)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

### Test sample of tokenizing

In [15]:
text = df['content'].iloc[0]
print(text)

Title: LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO] [SEP] Body: No comment is expected from Barack Obama Members of the #FYF911 or #FukYoFlag and #BlackLivesMatter movements called for the lynching and hanging of white people and cops. They encouraged others on a radio show Tuesday night to  turn the tide  and kill white people and cops to send a message about the killing of black people in America.One of the F***YoFlag organizers is called  Sunshine.  She has a radio blog show hosted from Texas called,  Sunshine s F***ing Opinion Radio Show. A snapshot of her #FYF911 @LOLatWhiteFear Twitter page at 9:53 p.m. shows that she was urging supporters to  Call now!! #fyf911 tonight we continue to dismantle the illusion of white Below is a SNAPSHOT Twitter Radio Call Invite   #FYF911The radio show aired at 10:00 p.m. eastern standard time.During the show, callers clearly call for  lynching  and  killing  of white people.A 2:39 minute clip from the radio show can be heard here. It was provided to Breitbart Texas by someone who would like to be referred to as  Hannibal.  He has already received death threats as a result of interrupting #FYF911 conference calls.An unidentified black man said  when those mother f**kers are by themselves, that s when when we should start f***ing them up. Like they do us, when a bunch of them ni**ers takin  one of us out, that s how we should roll up.  He said,  Cause we already roll up in gangs anyway. There should be six or seven black mother f**ckers, see that white person, and then lynch their ass. Let s turn the tables. They conspired that if  cops started losing people,  then  there will be a state of emergency. He speculated that one of two things would happen,  a big-ass [R s?????] war,  or  ni**ers, they are going to start backin  up. We are already getting killed out here so what the f**k we got to lose? Sunshine could be heard saying,  Yep, that s true. That s so f**king true. He said,  We need to turn the tables on them. Our kids are getting shot out here. Somebody needs to become a sacrifice on their side.He said,  Everybody ain t down for that s**t, or whatever, but like I say, everybody has a different position of war.  He continued,  Because they don t give a f**k anyway.  He said again,  We might as well utilized them for that s**t and turn the tables on these n**ers. He said, that way  we can start lookin  like we ain t havin  that many casualties, and there can be more causalities on their side instead of ours. They are out their killing black people, black lives don t matter, that s what those mother f**kers   so we got to make it matter to them. Find a mother f**ker that is alone. Snap his ass, and then f***in hang him from a damn tree. Take a picture of it and then send it to the mother f**kers. We  just need one example,  and  then people will start watchin .  This will turn the tables on s**t, he said. He said this will start  a trickle-down effect.  He said that when one white person is hung and then they are just  flat-hanging,  that will start the  trickle-down effect.  He continued,  Black people are good at starting trends. He said that was how  to get the upper-hand. Another black man spoke up saying they needed to kill  cops that are killing us. The first black male said,  That will be the best method right there. Breitbart Texas previously reported how Sunshine was upset when  racist white people  infiltrated and disrupted one of her conference calls. She subsequently released the phone number of one of the infiltrators. The veteran immediately started receiving threatening calls.One of the #F***YoFlag movement supporters allegedly told a veteran who infiltrated their publicly posted conference call,  We are going to rape and gut your pregnant wife, and your f***ing piece of sh*t unborn creature will be hung from a tree. Breitbart Texas previously encountered Sunshine at a Sandra Bland protest at the Waller County Jail in Texas, where she said all white people should be killed. She told journalists and photographers,  You see this nappy-ass hair on my head?   That means I am one of those more militant Negroes.  She said she was at the protest because  these redneck mother-f**kers murdered Sandra Bland because she had nappy hair like me. #FYF911 black radicals say they will be holding the  imperial powers  that are actually responsible for the terrorist attacks on September 11th accountable on that day, as reported by Breitbart Texas. There are several websites and Twitter handles for the movement. Palmetto Star  describes himself as one of the head organizers. He said in a YouTube video that supporters will be burning their symbols of  the illusion of their superiority,  their  false white supremacy,  like the American flag, the British flag, police uniforms, and Ku Klux Klan hoods.Sierra McGrone or  Nocturnus Libertus  posted,  you too can help a young Afrikan clean their a** with the rag of oppression.  She posted two photos, one that appears to be herself, and a photo of a black man, wiping their naked butts with the American flag.For entire story: Breitbart News

In [16]:
tokens = tokenizer(text)
print(tokens)

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1238 > 512). Running this sequence through the model will result in indexing errors

{'input_ids': [101, 2516, 1024, 2375, 7285, 2006, 2152, 9499, 2206, 8767, 2114, 10558, 1998, 12461, 2006, 1023, 1011, 2340, 3762, 1001, 2304, 3669, 6961, 18900, 3334, 1998, 1001, 1042, 2100, 2546, 2683, 14526, 15554, 1031, 2678, 1033, 102, 2303, 1024, 2053, 7615, 2003, 3517, 2013, 13857, 8112, 2372, 1997, 1996, 1001, 1042, 2100, 2546, 2683, 14526, 2030, 1001, 11865, 4801, 11253, 17802, 1998, 1001, 2304, 3669, 6961, 18900, 3334, 5750, 2170, 2005, 1996, 11404, 2075, 1998, 5689, 1997, 2317, 2111, 1998, 10558, 1012, 2027, 6628, 2500, 2006, 1037, 2557, 2265, 9857, 2305, 2000, 2735, 1996, 10401, 1998, 3102, 2317, 2111, 1998, 10558, 2000, 4604, 1037, 4471, 2055, 1996, 4288, 1997, 2304, 2111, 1999, 2637, 1012, 2028, 1997, 1996, 1042, 1008, 1008, 1008, 10930, 10258, 8490, 18829, 2003, 2170, 9609, 1012, 2016, 2038, 1037, 2557, 9927, 2265, 4354, 2013, 3146, 2170, 1010, 9609, 1055, 1042, 1008, 1008, 1008, 13749, 5448, 2557, 2265, 1012, 1037, 20057, 12326, 1997, 2014, 1001, 1042, 2100, 2546, 2683, 14526, 1030, 15137, 2102, 2860, 16584, 27235, 2906, 10474, 3931, 2012, 1023, 1024, 5187, 1052, 1012, 1049, 1012, 3065, 2008, 2016, 2001, 14328, 6793, 2000, 2655, 2085, 999, 999, 1001, 1042, 2100, 2546, 2683, 14526, 3892, 2057, 3613, 2000, 4487, 11512, 9286, 1996, 12492, 1997, 2317, 2917, 2003, 1037, 20057, 12326, 10474, 2557, 2655, 13260, 1001, 1042, 2100, 2546, 2683, 14526, 10760, 2557, 2265, 4836, 2012, 2184, 1024, 4002, 1052, 1012, 1049, 1012, 2789, 3115, 2051, 1012, 2076, 1996, 2265, 1010, 20587, 2015, 4415, 2655, 2005, 11404, 2075, 1998, 4288, 1997, 2317, 2111, 1012, 1037, 1016, 1024, 4464, 3371, 12528, 2013, 1996, 2557, 2265, 2064, 2022, 2657, 2182, 1012, 2009, 2001, 3024, 2000, 7987, 20175, 8237, 2102, 3146, 2011, 2619, 2040, 2052, 2066, 2000, 2022, 3615, 2000, 2004, 24181, 1012, 2002, 2038, 2525, 2363, 2331, 8767, 2004, 1037, 2765, 1997, 22602, 1001, 1042, 2100, 2546, 2683, 14526, 3034, 4455, 1012, 2019, 20293, 2304, 2158, 2056, 2043, 2216, 2388, 1042, 1008, 1008, 17710, 2869, 2024, 2011, 3209, 1010, 2008, 1055, 2043, 2043, 2057, 2323, 2707, 1042, 1008, 1008, 1008, 13749, 2068, 2039, 1012, 2066, 2027, 2079, 2149, 1010, 2043, 1037, 9129, 1997, 2068, 9152, 1008, 1008, 9413, 2015, 27006, 2378, 2028, 1997, 2149, 2041, 1010, 2008, 1055, 2129, 2057, 2323, 4897, 2039, 1012, 2002, 2056, 1010, 3426, 2057, 2525, 4897, 2039, 1999, 18542, 4312, 1012, 2045, 2323, 2022, 2416, 2030, 2698, 2304, 2388, 1042, 1008, 1008, 23616, 2545, 1010, 2156, 2008, 2317, 2711, 1010, 1998, 2059, 11404, 2037, 4632, 1012, 2292, 1055, 2735, 1996, 7251, 1012, 2027, 9530, 13102, 27559, 2008, 2065, 10558, 2318, 3974, 2111, 1010, 2059, 2045, 2097, 2022, 1037, 2110, 1997, 5057, 1012, 2002, 15520, 2008, 2028, 1997, 2048, 2477, 2052, 4148, 1010, 1037, 2502, 1011, 4632, 1031, 1054, 1055, 1029, 1029, 1029, 1029, 1029, 1033, 2162, 1010, 2030, 9152, 1008, 1008, 9413, 2015, 1010, 2027, 2024, 2183, 2000, 2707, 2067, 2378, 2039, 1012, 2057, 2024, 2525, 2893, 2730, 2041, 2182, 2061, 2054, 1996, 1042, 1008, 1008, 1047, 2057, 2288, 2000, 4558, 1029, 9609, 2071, 2022, 2657, 3038, 1010, 15624, 1010, 2008, 1055, 2995, 1012, 2008, 1055, 2061, 1042, 1008, 1008, 2332, 2995, 1012, 2002, 2056, 1010, 2057, 2342, 2000, 2735, 1996, 7251, 2006, 2068, 1012, 2256, 4268, 2024, 2893, 2915, 2041, 2182, 1012, 8307, 3791, 2000, 2468, 1037, 8688, 2006, 2037, 2217, 1012, 2002, 2056, 1010, 7955, 7110, 1056, 2091, 2005, 2008, 1055, 1008, 1008, 1056, 1010, 2030, 3649, 1010, 2021, 2066, 1045, 2360, 1010, 7955, 2038, 1037, 2367, 2597, 1997, 2162, 1012, 2002, 2506, 1010, 2138, 2027, 2123, 1056, 2507, 1037, 1042, 1008, 1008, 1047, 4312, 1012, 2002, 2056, 2153, 1010, 2057, 2453, 2004, 2092, 12550, 2068, 2005, 2008, 1055, 1008, 1008, 1056, 1998, 2735, 1996, 7251, 2006, 2122, 1050, 1008, 1008, 9413, 2015, 1012, 2002, 2056, 1010, 2008, 2126, 2057, 2064, 2707, 2298, 2378, 2066, 2057, 7110, 1056, 5292, 6371, 2008, 2116, 8664, 1010, 1998, 2045, 2064, 2022, 2062, 28102, 6447, 2006, 2037, 2217, 2612, 1997, 14635, 1012, 2027, 2024, 2041, 2037, 4288, 2304, 2111, 1010, 2304, 3268, 2123, 1056, 3043, 1010, 2008, 1055, 2054, 2216, 2388, 1042, 1008, 1008, 17710, 2869, 2061, 2057, 2288, 2000, 2191, 2009, 3043, 2000, 2068, 1012, 2424, 1037, 2388, 1042, 1008, 1008, 17710, 2099, 2008, 2003, 2894, 1012, 10245, 2010, 4632, 1010, 1998, 2059, 1042, 1008, 1008, 1008, 1999, 6865, 2032, 2013, 1037, 4365, 3392, 1012, 2202, 1037, 3861, 1997, 2009, 1998, 2059, 4604, 2009, 2000, 1996, 2388, 1042, 1008, 1008, 17710, 2869, 1012, 2057, 2074, 2342, 2028, 2742, 1010, 1998, 2059, 2111, 2097, 2707, 3422, 2378, 1012, 2023, 2097, 2735, 1996, 7251, 2006, 1055, 1008, 1008, 1056, 1010, 2002, 2056, 1012, 2002, 2056, 2023, 2097, 2707, 1037, 26027, 1011, 2091, 3466, 1012, 2002, 2056, 2008, 2043, 2028, 2317, 2711, 2003, 5112, 1998, 2059, 2027, 2024, 2074, 4257, 1011, 5689, 1010, 2008, 2097, 2707, 1996, 26027, 1011, 2091, 3466, 1012, 2002, 2506, 1010, 2304, 2111, 2024, 2204, 2012, 3225, 12878, 1012, 2002, 2056, 2008, 2001, 2129, 2000, 2131, 1996, 3356, 1011, 2192, 1012, 2178, 2304, 2158, 3764, 2039, 3038, 2027, 2734, 2000, 3102, 10558, 2008, 2024, 4288, 2149, 1012, 1996, 2034, 2304, 3287, 2056, 1010, 2008, 2097, 2022, 1996, 2190, 4118, 2157, 2045, 1012, 7987, 20175, 8237, 2102, 3146, 3130, 2988, 2129, 9609, 2001, 6314, 2043, 16939, 2317, 2111, 29543, 2094, 1998, 20275, 2028, 1997, 2014, 3034, 4455, 1012, 2016, 3525, 2207, 1996, 3042, 2193, 1997, 2028, 1997, 1996, 1999, 8873, 7096, 16259, 2015, 1012, 1996, 8003, 3202, 2318, 4909, 8701, 4455, 1012, 2028, 1997, 1996, 1001, 1042, 1008, 1008, 1008, 10930, 10258, 8490, 2929, 6793, 9382, 2409, 1037, 8003, 2040, 29543, 2094, 2037, 7271, 6866, 3034, 2655, 1010, 2057, 2024, 2183, 2000, 9040, 1998, 9535, 2115, 6875, 2564, 1010, 1998, 2115, 1042, 1008, 1008, 1008, 13749, 3538, 1997, 14021, 1008, 1056, 4895, 10280, 6492, 2097, 2022, 5112, 2013, 1037, 3392, 1012, 7987, 20175, 8237, 2102, 3146, 3130, 8567, 9609, 2012, 1037, 12834, 20857, 6186, 2012, 1996, 23550, 2221, 7173, 1999, 3146, 1010, 2073, 2016, 2056, 2035, 2317, 2111, 2323, 2022, 2730, 1012, 2016, 2409, 8845, 1998, 17008, 1010, 2017, 2156, 2023, 18996, 7685, 1011, 4632, 2606, 2006, 2026, 2132, 1029, 2008, 2965, 1045, 2572, 2028, 1997, 2216, 2062, 16830, 12593, 2229, 1012, 2016, 2056, 2016, 2001, 2012, 1996, 6186, 2138, 2122, 2417, 18278, 2388, 1011, 1042, 1008, 1008, 17710, 2869, 7129, 12834, 20857, 2138, 2016, 2018, 18996, 7685, 2606, 2066, 2033, 1012, 1001, 1042, 2100, 2546, 2683, 14526, 2304, 23618, 2360, 2027, 2097, 2022, 3173, 1996, 4461, 4204, 2008, 2024, 2941, 3625, 2005, 1996, 9452, 4491, 2006, 2244, 6252, 26771, 2006, 2008, 2154, 1010, 2004, 2988, 2011, 7987, 20175, 8237, 2102, 3146, 1012, 2045, 2024, 2195, 11744, 1998, 10474, 16024, 2005, 1996, 2929, 1012, 5340, 20082, 2732, 5577, 2370, 2004, 2028, 1997, 1996, 2132, 18829, 1012, 2002, 2056, 1999, 1037, 7858, 2678, 2008, 6793, 2097, 2022, 5255, 2037, 9255, 1997, 1996, 12492, 1997, 2037, 19113, 1010, 2037, 6270, 2317, 22006, 1010, 2066, 1996, 2137, 5210, 1010, 1996, 2329, 5210, 1010, 2610, 11408, 1010, 1998, 13970, 1047, 25148, 26613, 7415, 2015, 1012, 7838, 11338, 16523, 5643, 2030, 2053, 6593, 14287, 2271, 5622, 8296, 2271, 6866, 1010, 2017, 2205, 2064, 2393, 1037, 2402, 21358, 23778, 2078, 4550, 2037, 1037, 1008, 1008, 2007, 1996, 17768, 1997, 20489, 1012, 2016, 6866, 2048, 7760, 1010, 2028, 2008, 3544, 2000, 2022, 2841, 1010, 1998, 1037, 6302, 1997, 1037, 2304, 2158, 1010, 14612, 2037, 6248, 10007, 2015, 2007, 1996, 2137, 5210, 1012, 2005, 2972, 2466, 1024, 7987, 20175, 8237, 2102, 2739, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [30]:
def tokenize(batch):
    return tokenizer(
        batch['content'],
        padding='max_length',
        truncation=True,
        max_length=512
    )

In [18]:
from datasets import Dataset

dataset = Dataset.from_pandas(df)

In [31]:
tokenized_dataset = dataset.map(tokenize, batched=True)

Map:   0%|          | 0/57229 [00:00<?, ? examples/s]

Map:   0%|          | 0/14308 [00:00<?, ? examples/s]

In [20]:
print(tokenized_dataset[0])

{'Unnamed: 0': 0, 'title': 'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO]', 'text': 'No comment is expected from Barack Obama Members of the #FYF911 or #FukYoFlag and #BlackLivesMatter movements called for the lynching and hanging of white people and cops. They encouraged others on a radio show Tuesday night to  turn the tide  and kill white people and cops to send a message about the killing of black people in America.One of the F***YoFlag organizers is called  Sunshine.  She has a radio blog show hosted from Texas called,  Sunshine s F***ing Opinion Radio Show. A snapshot of her #FYF911 @LOLatWhiteFear Twitter page at 9:53 p.m. shows that she was urging supporters to  Call now!! #fyf911 tonight we continue to dismantle the illusion of white Below is a SNAPSHOT Twitter Radio Call Invite   #FYF911The radio show aired at 10:00 p.m. eastern standard time.During the show, callers clearly call for  lynching  and  killing  of white people.A 2:39 minute clip from the radio show can be heard here. It was provided to Breitbart Texas by someone who would like to be referred to as  Hannibal.  He has already received death threats as a result of interrupting #FYF911 conference calls.An unidentified black man said  when those mother f**kers are by themselves, that s when when we should start f***ing them up. Like they do us, when a bunch of them ni**ers takin  one of us out, that s how we should roll up.  He said,  Cause we already roll up in gangs anyway. There should be six or seven black mother f**ckers, see that white person, and then lynch their ass. Let s turn the tables. They conspired that if  cops started losing people,  then  there will be a state of emergency. He speculated that one of two things would happen,  a big-ass [R s?????] war,  or  ni**ers, they are going to start backin  up. We are already getting killed out here so what the f**k we got to lose? Sunshine could be heard saying,  Yep, that s true. That s so f**king true. He said,  We need to turn the tables on them. Our kids are getting shot out here. Somebody needs to become a sacrifice on their side.He said,  Everybody ain t down for that s**t, or whatever, but like I say, everybody has a different position of war.  He continued,  Because they don t give a f**k anyway.  He said again,  We might as well utilized them for that s**t and turn the tables on these n**ers. He said, that way  we can start lookin  like we ain t havin  that many casualties, and there can be more causalities on their side instead of ours. They are out their killing black people, black lives don t matter, that s what those mother f**kers   so we got to make it matter to them. Find a mother f**ker that is alone. Snap his ass, and then f***in hang him from a damn tree. Take a picture of it and then send it to the mother f**kers. We  just need one example,  and  then people will start watchin .  This will turn the tables on s**t, he said. He said this will start  a trickle-down effect.  He said that when one white person is hung and then they are just  flat-hanging,  that will start the  trickle-down effect.  He continued,  Black people are good at starting trends. He said that was how  to get the upper-hand. Another black man spoke up saying they needed to kill  cops that are killing us. The first black male said,  That will be the best method right there. Breitbart Texas previously reported how Sunshine was upset when  racist white people  infiltrated and disrupted one of her conference calls. She subsequently released the phone number of one of the infiltrators. The veteran immediately started receiving threatening calls.One of the #F***YoFlag movement supporters allegedly told a veteran who infiltrated their publicly posted conference call,  We are going to rape and gut your pregnant wife, and your f***ing piece of sh*t unborn creature will be hung from a tree. Breitbart Texas previously encountered Sunshine at a Sandra Bland protest at the Waller County Jail in Texas, where she said all white people should be killed. She told journalists and photographers,  You see this nappy-ass hair on my head?   That means I am one of those more militant Negroes.  She said she was at the protest because  these redneck mother-f**kers murdered Sandra Bland because she had nappy hair like me. #FYF911 black radicals say they will be holding the  imperial powers  that are actually responsible for the terrorist attacks on September 11th accountable on that day, as reported by Breitbart Texas. There are several websites and Twitter handles for the movement. Palmetto Star  describes himself as one of the head organizers. He said in a YouTube video that supporters will be burning their symbols of  the illusion of their superiority,  their  false white supremacy,  like the American flag, the British flag, police uniforms, and Ku Klux Klan hoods.Sierra McGrone or  Nocturnus Libertus  posted,  you too can help a young Afrikan clean their a** with the rag of oppression.  She posted two photos, one that appears to be herself, and a photo of a black man, wiping their naked butts with the American flag.For entire story: Breitbart News', 'label': 1, 'content': 'Title: LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO] [SEP] Body: No comment is expected from Barack Obama Members of the #FYF911 or #FukYoFlag and #BlackLivesMatter movements called for the lynching and hanging of white people and cops. They encouraged others on a radio show Tuesday night to  turn the tide  and kill white people and cops to send a message about the killing of black people in America.One of the F***YoFlag organizers is called  Sunshine.  She has a radio blog show hosted from Texas called,  Sunshine s F***ing Opinion Radio Show. A snapshot of her #FYF911 @LOLatWhiteFear Twitter page at 9:53 p.m. shows that she was urging supporters to  Call now!! #fyf911 tonight we continue to dismantle the illusion of white Below is a SNAPSHOT Twitter Radio Call Invite   #FYF911The radio show aired at 10:00 p.m. eastern standard time.During the show, callers clearly call for  lynching  and  killing  of white people.A 2:39 minute clip from the radio show can be heard here. It was provided to Breitbart Texas by someone who would like to be referred to as  Hannibal.  He has already received death threats as a result of interrupting #FYF911 conference calls.An unidentified black man said  when those mother f**kers are by themselves, that s when when we should start f***ing them up. Like they do us, when a bunch of them ni**ers takin  one of us out, that s how we should roll up.  He said,  Cause we already roll up in gangs anyway. There should be six or seven black mother f**ckers, see that white person, and then lynch their ass. Let s turn the tables. They conspired that if  cops started losing people,  then  there will be a state of emergency. He speculated that one of two things would happen,  a big-ass [R s?????] war,  or  ni**ers, they are going to start backin  up. We are already getting killed out here so what the f**k we got to lose? Sunshine could be heard saying,  Yep, that s true. That s so f**king true. He said,  We need to turn the tables on them. Our kids are getting shot out here. Somebody needs to become a sacrifice on their side.He said,  Everybody ain t down for that s**t, or whatever, but like I say, everybody has a different position of war.  He continued,  Because they don t give a f**k anyway.  He said again,  We might as well utilized them for that s**t and turn the tables on these n**ers. He said, that way  we can start lookin  like we ain t havin  that many casualties, and there can be more causalities on their side instead of ours. They are out their killing black people, black lives don t matter, that s what those mother f**kers   so we got to make it matter to them. Find a mother f**ker that is alone. Snap his ass, and then f***in hang him from a damn tree. Take a picture of it and then send it to the mother f**kers. We  just need one example,  and  then people will start watchin .  This will turn the tables on s**t, he said. He said this will start  a trickle-down effect.  He said that when one white person is hung and then they are just  flat-hanging,  that will start the  trickle-down effect.  He continued,  Black people are good at starting trends. He said that was how  to get the upper-hand. Another black man spoke up saying they needed to kill  cops that are killing us. The first black male said,  That will be the best method right there. Breitbart Texas previously reported how Sunshine was upset when  racist white people  infiltrated and disrupted one of her conference calls. She subsequently released the phone number of one of the infiltrators. The veteran immediately started receiving threatening calls.One of the #F***YoFlag movement supporters allegedly told a veteran who infiltrated their publicly posted conference call,  We are going to rape and gut your pregnant wife, and your f***ing piece of sh*t unborn creature will be hung from a tree. Breitbart Texas previously encountered Sunshine at a Sandra Bland protest at the Waller County Jail in Texas, where she said all white people should be killed. She told journalists and photographers,  You see this nappy-ass hair on my head?   That means I am one of those more militant Negroes.  She said she was at the protest because  these redneck mother-f**kers murdered Sandra Bland because she had nappy hair like me. #FYF911 black radicals say they will be holding the  imperial powers  that are actually responsible for the terrorist attacks on September 11th accountable on that day, as reported by Breitbart Texas. There are several websites and Twitter handles for the movement. Palmetto Star  describes himself as one of the head organizers. He said in a YouTube video that supporters will be burning their symbols of  the illusion of their superiority,  their  false white supremacy,  like the American flag, the British flag, police uniforms, and Ku Klux Klan hoods.Sierra McGrone or  Nocturnus Libertus  posted,  you too can help a young Afrikan clean their a** with the rag of oppression.  She posted two photos, one that appears to be herself, and a photo of a black man, wiping their naked butts with the American flag.For entire story: Breitbart News', '__index_level_0__': 0, 'input_ids': [101, 2516, 1024, 2375, 7285, 2006, 2152, 9499, 2206, 8767, 2114, 10558, 1998, 12461, 2006, 1023, 1011, 2340, 3762, 1001, 2304, 3669, 6961, 18900, 3334, 1998, 1001, 1042, 2100, 2546, 2683, 14526, 15554, 1031, 2678, 1033, 102, 2303, 1024, 2053, 7615, 2003, 3517, 2013, 13857, 8112, 2372, 1997, 1996, 1001, 1042, 2100, 2546, 2683, 14526, 2030, 1001, 11865, 4801, 11253, 17802, 1998, 1001, 2304, 3669, 6961, 18900, 3334, 5750, 2170, 2005, 1996, 11404, 2075, 1998, 5689, 1997, 2317, 2111, 1998, 10558, 1012, 2027, 6628, 2500, 2006, 1037, 2557, 2265, 9857, 2305, 2000, 2735, 1996, 10401, 1998, 3102, 2317, 2111, 1998, 10558, 2000, 4604, 1037, 4471, 2055, 1996, 4288, 1997, 2304, 2111, 1999, 2637, 1012, 2028, 1997, 1996, 1042, 1008, 1008, 1008, 10930, 10258, 8490, 18829, 2003, 2170, 9609, 1012, 2016, 2038, 1037, 2557, 9927, 2265, 4354, 2013, 3146, 2170, 1010, 9609, 1055, 1042, 1008, 1008, 1008, 13749, 5448, 2557, 2265, 1012, 1037, 20057, 12326, 1997, 2014, 1001, 1042, 2100, 2546, 2683, 14526, 1030, 15137, 2102, 2860, 16584, 27235, 2906, 10474, 3931, 2012, 1023, 1024, 5187, 1052, 1012, 1049, 1012, 3065, 2008, 2016, 2001, 14328, 6793, 2000, 2655, 2085, 999, 999, 1001, 1042, 2100, 2546, 2683, 14526, 3892, 2057, 3613, 2000, 4487, 11512, 9286, 1996, 12492, 1997, 2317, 2917, 2003, 1037, 20057, 12326, 10474, 2557, 2655, 13260, 1001, 1042, 2100, 2546, 2683, 14526, 10760, 2557, 2265, 4836, 2012, 2184, 1024, 4002, 1052, 1012, 1049, 1012, 2789, 3115, 2051, 1012, 2076, 1996, 2265, 1010, 20587, 2015, 4415, 2655, 2005, 11404, 2075, 1998, 4288, 1997, 2317, 2111, 1012, 1037, 1016, 1024, 4464, 3371, 12528, 2013, 1996, 2557, 2265, 2064, 2022, 2657, 2182, 1012, 2009, 2001, 3024, 2000, 7987, 20175, 8237, 2102, 3146, 2011, 2619, 2040, 2052, 2066, 2000, 2022, 3615, 2000, 2004, 24181, 1012, 2002, 2038, 2525, 2363, 2331, 8767, 2004, 1037, 2765, 1997, 22602, 1001, 1042, 2100, 2546, 2683, 14526, 3034, 4455, 1012, 2019, 20293, 2304, 2158, 2056, 2043, 2216, 2388, 1042, 1008, 1008, 17710, 2869, 2024, 2011, 3209, 1010, 2008, 1055, 2043, 2043, 2057, 2323, 2707, 1042, 1008, 1008, 1008, 13749, 2068, 2039, 1012, 2066, 2027, 2079, 2149, 1010, 2043, 1037, 9129, 1997, 2068, 9152, 1008, 1008, 9413, 2015, 27006, 2378, 2028, 1997, 2149, 2041, 1010, 2008, 1055, 2129, 2057, 2323, 4897, 2039, 1012, 2002, 2056, 1010, 3426, 2057, 2525, 4897, 2039, 1999, 18542, 4312, 1012, 2045, 2323, 2022, 2416, 2030, 2698, 2304, 2388, 1042, 1008, 1008, 23616, 2545, 1010, 2156, 2008, 2317, 2711, 1010, 1998, 2059, 11404, 2037, 4632, 1012, 2292, 1055, 2735, 1996, 7251, 1012, 2027, 9530, 13102, 27559, 2008, 2065, 10558, 2318, 3974, 2111, 1010, 2059, 2045, 2097, 2022, 1037, 2110, 1997, 5057, 1012, 2002, 15520, 2008, 2028, 1997, 2048, 2477, 2052, 4148, 1010, 1037, 2502, 1011, 4632, 1031, 1054, 1055, 1029, 1029, 1029, 1029, 1029, 1033, 2162, 1010, 2030, 9152, 1008, 1008, 9413, 2015, 1010, 2027, 2024, 2183, 2000, 2707, 2067, 2378, 2039, 1012, 2057, 2024, 2525, 2893, 2730, 2041, 2182, 2061, 2054, 1996, 1042, 1008, 1008, 1047, 2057, 2288, 2000, 4558, 1029, 9609, 2071, 2022, 2657, 3038, 1010, 15624, 1010, 2008, 1055, 2995, 1012, 2008, 1055, 2061, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [21]:
tokenized_dataset = tokenized_dataset.rename_column("label", "labels") #Adjustment

In [22]:
tokenized_dataset.set_format(
    type='torch',
    columns=['input_ids', 'attention_mask', 'labels']
)

In [23]:
dataset = tokenized_dataset.train_test_split(test_size=0.2)
train_dataset = dataset['train']
test_dataset = dataset['test']

In [38]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir='the model',
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="steps",
    logging_steps=200,
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,   # effective train batch = 8
    weight_decay=0.01,
    num_train_epochs=3,
    fp16=True,                       # use only if your GPU/notebook supports it
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    report_to="none",
)

In [24]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="binary", zero_division=0
    )
    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1,
    }

In [39]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

In [40]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=5367, training_loss=0.058145205946148096, metrics={'train_runtime': 5286.0238, 'train_samples_per_second': 32.479, 'train_steps_per_second': 1.015, 'total_flos': 4.517274776159232e+16, 'train_loss': 0.058145205946148096, 'epoch': 3.0})

In [41]:
trainer.save_model("fake_news_bert_model")
tokenizer.save_pretrained("fake_news_bert_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('fake_news_bert_model/tokenizer_config.json',
 'fake_news_bert_model/tokenizer.json')

In [45]:
import torch

def predict_news(text):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=512
    )

    # ✅ move inputs to GPU
    inputs = {key: val.to(device) for key, val in inputs.items()}

    # ✅ make sure model is on GPU too
    model.to(device)
    model.eval()

    with torch.no_grad():
        outputs = model(**inputs)

    probs = torch.softmax(outputs.logits, dim=1)

    pred = torch.argmax(probs).item()

    label = "Fake" if pred == 1 else "Real"
    confidence = probs[0][pred].item()

    return label, confidence

In [43]:
text1 = """
BREAKING: Scientists CONFIRM that drinking coffee cures all diseases instantly!!!
Experts say this miracle discovery is being hidden by big pharmaceutical companies.
Thousands of people have already been cured overnight. Share this before it gets deleted!
"""  #Fake

text2 = """
The Ministry of Health announced on Tuesday that new regulations will be introduced
to improve hospital safety standards. Officials stated that the policy will be
implemented gradually over the next six months, with regular evaluations.
""" #Real

text3 = """
A recent report claims that a secret group of researchers has developed a device
that can control weather patterns globally. While no official confirmation has been
provided, sources suggest governments are already using the technology.
"""#Triky fake

text4 = """
According to Reuters, global oil prices rose by 2% on Monday following supply concerns.
Analysts attribute the increase to ongoing geopolitical tensions affecting production.
"""#Real

In [51]:
predict_news(text3)

('Real', 0.999713122844696)

In [52]:
# =========================
# Test your model on examples
# =========================

test_samples = [
    # 🟢 REAL
    "The Federal Reserve announced it will keep interest rates unchanged while monitoring inflation trends and economic growth.",
    "The United Nations held an emergency meeting to discuss climate change policies and international cooperation efforts.",
    "Apple unveiled its latest iPhone model featuring improved battery life and enhanced camera capabilities during its annual event.",

    # 🔴 FAKE
    "Scientists have discovered a way to make humans live up to 300 years by drinking a special herbal tea every day.",
    "A man claims he built a working time machine in his garage and traveled to the year 3025.",
    "Doctors confirm that eating chocolate three times a day completely eliminates the risk of all diseases.",

    # ⚠️ TRICKY
    "Experts suggest that certain natural remedies may help boost the immune system, though more research is needed.",
    "A viral post claims that a new study proves vaccines are harmful, but no scientific evidence supports this claim.",
    "Some people believe that drinking hot water frequently can prevent serious illnesses, although this is not medically proven."
]

# Run predictions
for i, text in enumerate(test_samples, 1):
    label, confidence = predict_news(text)
    
    print(f"\nExample {i}")
    print(f"Text: {text}")
    print(f"Prediction: {label}")
    print(f"Confidence: {confidence:.4f}")
    print("-" * 80)

Example 1
Text: The Federal Reserve announced it will keep interest rates unchanged while monitoring inflation trends and economic growth.
Prediction: Real
Confidence: 0.9999
--------------------------------------------------------------------------------

Example 2
Text: The United Nations held an emergency meeting to discuss climate change policies and international cooperation efforts.
Prediction: Real
Confidence: 1.0000
--------------------------------------------------------------------------------

Example 3
Text: Apple unveiled its latest iPhone model featuring improved battery life and enhanced camera capabilities during its annual event.
Prediction: Real
Confidence: 0.9995
--------------------------------------------------------------------------------

Example 4
Text: Scientists have discovered a way to make humans live up to 300 years by drinking a special herbal tea every day.
Prediction: Fake
Confidence: 0.8163
--------------------------------------------------------------------------------

Example 5
Text: A man claims he built a working time machine in his garage and traveled to the year 3025.
Prediction: Fake
Confidence: 0.8753
--------------------------------------------------------------------------------

Example 6
Text: Doctors confirm that eating chocolate three times a day completely eliminates the risk of all diseases.
Prediction: Real
Confidence: 0.9996
--------------------------------------------------------------------------------

Example 7
Text: Experts suggest that certain natural remedies may help boost the immune system, though more research is needed.
Prediction: Real
Confidence: 0.9999
--------------------------------------------------------------------------------

Example 8
Text: A viral post claims that a new study proves vaccines are harmful, but no scientific evidence supports this claim.
Prediction: Real
Confidence: 0.9567
--------------------------------------------------------------------------------

Example 9
Text: Some people believe that drinking hot water frequently can prevent serious illnesses, although this is not medically proven.
Prediction: Real
Confidence: 0.9971
--------------------------------------------------------------------------------

In [55]:
text_tricky_fake = """
A recently circulated report claims that a group of international scientists has successfully developed a new type of “self-charging” battery capable of powering electronic devices indefinitely without the need for external energy sources. According to the report, the technology relies on a novel combination of quantum materials and ambient electromagnetic radiation, allowing the battery to continuously recharge itself from the surrounding environment.

The research, allegedly conducted by a consortium of universities across Europe and Asia, was said to have been published in a leading scientific journal earlier this year. The report states that early prototypes have already been tested in smartphones and electric vehicles, showing promising results with devices running for months without needing to be plugged in.

Supporters of the claim argue that this breakthrough could revolutionize the global energy industry by eliminating the need for traditional charging infrastructure. They suggest it could significantly reduce electronic waste and lower the environmental impact of battery production.

However, several experts have expressed skepticism regarding the feasibility of such technology. Critics point out that the concept appears to violate fundamental principles of energy conservation, noting that no peer-reviewed evidence has been widely recognized in the scientific community. Additionally, major journals and institutions have not officially confirmed the publication mentioned in the report.

Despite these concerns, the story has gained widespread attention on social media platforms, where users have shared it as evidence of a major technological leap being kept from the public. Some posts have even suggested that large energy corporations may attempt to suppress the innovation to protect existing business models.

At this time, no verified demonstration or independent replication of the technology has been publicly documented, and the institutions named in the report have not issued formal statements confirming their involvement.
"""



label, confidence = predict_news(text_tricky_fake)
print(label, confidence)

Real 0.9961977601051331